- apps/simulator/src/components/blocks/RegularQuestions/MCQ/RegularMCQSSQuestionnaire.tsx
- Wrap MCQSS Regular Questionnaire form in Form Provider
- Arrange and Remove unused imports
> @enhancement/86ep6crbh/MCQSS-Add-form-provider

- apps/simulator/src/components/Header/Header.tsx
- packages/utils/hooks/useCountdown.ts
- Added Duration
- Added Time Remaining
- Create useCountdown
> @feature/86ep8fj54/Timer ft Time Remaining and Duration 

- apps/simulator/db.json
- apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
- apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPQuestionaire.tsx
- apps/simulator/src/core/schema/hcp/validation.ts
- apps/simulator/src/core/schema/useAtomic.ts
- apps/simulator/src/core/utils/hcpUtils.tsx
- apps/simulator/src/core/utils/useExtractBracket.tsx
- apps/simulator/src/core/utils/useHighlightedProcessor.tsx
- apps/simulator/src/core/utils/useParsedHCPLabelKey .tsx
- Creation of highlight component
- Highlight Validation
- Add hooks for extracting value inside brackets
- Code Isolation move function in utils folder
> @enhancement/86ep326fg/highlight validation ft highlight component

- packages/core-library/api/web/web-api-backoffice.ts
- packages/core-library/api/web/web-api.ts
- packages/core-library/components/blocks/AccountSetupBlock/AccountSetupBlock.tsx
- packages/core-library/components/blocks/AccountSetupBlock/AccountSetupForm.tsx
- packages/core-library/components/blocks/AccountSetupBlock/hooks.ts
- packages/core-library/components/blocks/AccountSetupBlock/validation.ts
- packages/core-library/config/index.ts
- packages/core-library/contents/cms/parse-cms.tsx
- packages/core-library/core/router.ts
- packages/core-library/ssr.ts
- Add Account form
- Create Api Entiry
- Account setup Validation
> @86epcnmrk #Added Form UI, Account Validation and Api Entiry

- apps/simulator/src/components/Footer/Footer.tsx
- apps/simulator/src/components/Header/Header.tsx
- apps/simulator/src/components/LoadablePageContents.tsx
- apps/simulator/src/components/blocks/RegularQuestions/MCQ/MCQBlock.tsx
- apps/simulator/src/components/parse-contents.tsx
- apps/simulator/src/core/context/AppContext.tsx
- apps/simulator/src/core/context/ProgressContext.tsx
- apps/simulator/src/core/hooks/useRegularSubmission.ts
- packages/core-library/core/hooks/useBusinessQueries.ts
- Integration of header loader
- Disable of button on submission
> @86eppgg8z #header loader integrations and disabling submit button on submission

- apps/web-customer/src/components/LoadablePageContent.tsx
- apps/web-customer/src/pages/shared/Layout.tsx
…authorized, some of the data and url there are mock
> @86epktzu7 #Prevention access for LoginPage when the user is already Authorized

- apps/web-backoffice-generic/src/pages/accountsetup.tsx
- packages/core-library/components/blocks/AccountSetupBlock/validation.ts
- packages/core-library/contexts/auth/AuthContext.tsx
- packages/core-library/core/utils/withAuth.tsx
- packages/core-library/types/types.ts
- Page Redirection to account setup when no user is created
- Comment account setup function for future purposes
> @86epr0mnq #Account detection and account setup redirection

- apps/web-backoffice-generic/src/core/constant/reportIssueMock.tsx
- apps/web-backoffice-generic/src/pages/reported-issues.tsx
- packages/core-library/components/DataGrid/DataGrid.tsx
- Added Reported Issues Page Viewer
- Extends Datagrid type
> @86epku5u9 #Report and Issue Viewer page

- apps/web-customer/src/components/ReportIssue/ReportIssueDialog.tsx
- apps/web-customer/src/components/ReportIssue/ReportIssueForm.tsx
- apps/web-customer/src/components/blocks/ContactBlock/ContactForm.tsx
- apps/web-customer/src/components/blocks/ContactBlock/ContactFormBlock.tsx
- apps/web-customer/src/components/blocks/ForgotPasswordBlock/ForgotPasswordBlock.tsx
- apps/web-customer/src/components/blocks/ForgotPasswordBlock/ForgotPasswordForm.tsx
- apps/web-customer/src/core/Schema/ReportIssueForm/validation.ts
- apps/web-customer/src/core/Schema/index.ts
- apps/web-customer/src/core/constant/ReportIssueMock/IssueMockData.ts
* Added Web Customer Report Issue Form
* Added Web Customer Report Issue Dialog
* Fixed schema routing
> Added Web Customer Report Issue

- apps/web-customer/src/components/blocks/HomePageBlocks/Pricing/PricingBlock.tsx
- apps/web-customer/src/components/blocks/OrderSummaryBlock/OrderSummaryBlock.tsx
- apps/web-customer/src/components/blocks/OrderSummaryBlock/useDecryptOrder.tsx
- apps/web-customer/src/components/blocks/index.ts
- apps/web-customer/src/pages/order-summary.tsx
- apps/web-customer/src/pages/payment.tsx
- packages/core-library/api/types.ts
- packages/core-library/api/web/web-api-backoffice.ts
- packages/core-library/contexts/BusinessQuery.tsx
- packages/core-library/contexts/stripe/StripeContext.tsx
- packages/core-library/core/hooks/useBusinessQueries.ts
- packages/core-library/utils/Decryption.ts
- Order summary UI
- Order summary integrations
- Payment intent with client secret key
> @86eprzjt3 #Order summary number integrations and Payment intent initialization

- apps/simulator/package.json
- apps/web-backoffice-generic/package.json
- apps/web-customer/package.json
- packages/core-library/hooks/index.ts
- packages/core-library/hooks/useSanitizeInputs.ts
- packages/core-library/package.json
- yarn.lock
- Install new dependency isomorphic-dompurify
- Creation of hooks for purifying inputs
> @86epd7ngu #Create a hook for purifying inputs and preventions of html injections

- apps/web-customer/src/components/blocks/HomePageBlocks/HowItWorks/HowItWorksBlock.tsx
Bug Fix : "/" in How it works Section
> @86epzaepq #Slash (/) Fixed in How It Works Section

- apps/web-customer/src/components/blocks/HomePageBlocks/Pricing/PricingBlock.tsx
- apps/web-customer/src/components/blocks/HomePageBlocks/Pricing/PricingComponent/PricingCard.tsx
- apps/web-customer/src/components/blocks/OrderCheckoutBlock/OrderCheckoutBlock.tsx
- apps/web-customer/src/components/blocks/OrderSummaryBlock/OrderSummaryBlock.tsx
Changes:
- Added (RN) and (PN) in order summary as per request of Client
- Dynamic Data in Payment Checkout
> @86epzggjz # Pricing-Page Dynamic Details

- .github/workflows/dev.yml
- apps/web-backoffice-generic/src/pages/shared/Layout.tsx
- packages/core-library/components/Button/Button.tsx
Change the button alignment into center
Fixed sidebar that flicks even when not authorized
> @86eq03ptq #Fixed the sidebar that flicks even not authorized 

- apps/web-backoffice-generic/src/core/schema/RegularSata/createRegularSATAQuestionSchema.ts
- packages/core-library/components/Radio/Radio.tsx
- packages/core-library/components/Textfield/TextField.tsx
- packages/core-library/components/blocks/AnswerOptions/AnswerOptions.tsx
- packages/core-library/components/blocks/AnswerOptions/blocks/MCQ/MCQ.tsx
- packages/core-library/components/blocks/AnswerOptions/blocks/SATA/SATA.tsx
- packages/core-library/components/blocks/AnswerOptions/content/StyledBox.tsx
- packages/core-library/components/index.ts
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/constants/constants.ts
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/CreateRegularQuestion.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/hooks/useRegularQuestionForm.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/useRegularQuestionForm.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/types.ts
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/validation.ts
- packages/core-library/tests/components/Blocks/AnswerOptions/AnswerOptions.test.tsx
- packages/core-library/tests/components/Blocks/AnswerOptions/blocks/MCQ.test.tsx
- packages/core-library/tests/components/Blocks/AnswerOptions/blocks/SATA.test.tsx
- packages/core-library/tests/components/Radio.tsx/Radio.test.tsx
- Create regular question questionnaire validation
- Fix default values bug on answer options
> @86epxqyub #Create regular question step 2 and validation

- apps/web-customer/src/components/blocks/NotFoundBlock/NotFoundBlock.tsx
> @86eq79wzb #Button width increased on mobile

- packages/core-library/components/GenericSidebar/Sidebar.tsx
> @86eq79ydp #Sidebar logo: change into darker variant

- package-lock.json
- packages/core-library/components/ReusableFooter/Footer.tsx
- yarn.lock
> @86eq79xhe #Footer-UI-Enhancement

- apps/web-customer/src/components/Cards/FlippableCard/FlipCard.tsx
- apps/web-customer/src/pages/index.css
enhancement: maintain hover effect on desktop and added clickable flip on mobile.
> @86eq79xcy #Added card flip on mobile

- packages/core-library/components/GenericDrawerLayout/DrawerLayout.tsx
- packages/core-library/components/GenericHeader/Header.tsx
- packages/core-library/components/GenericSidebar/Sidebar.tsx
This ticket addressed the displaying of sidebar even though it doesn't have any menu items
> @86eq79y5v #Sidebar Displays even with no content Fix

- apps/web-customer/src/components/blocks/LoginFormBlock/LoginForm.tsx
> @86eq60th2 #Added Login Responsiveness

- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/SettingsManagementPageForm.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/ChooseSettingsTypeStep.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/QuestionManagementSettingsTypeStep.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/QuestionManagement.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/CreateRegularQuestion.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/QuestionSummary.tsx
- packages/core-library/tests/components/Blocks/QuestionSummary.test.tsx
adding reset to the top back button 
implement reset if route change
> @86eq7pmwe #Regular question steps not reset if back button clicked

- packages/core-library/components/Popover/Popover.tsx
- packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentApproverForm.tsx
- packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerBlock.tsx
- packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerData.ts
- packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
- packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/validation.ts
- packages/core-library/system/app/internal/blocks/Hub/content/approval/steps/content/regular/ApprovalListView.tsx
- packages/core-library/system/app/internal/blocks/Hub/content/approval/steps/stepsconfig/regular/ApprovalSelectionSettings.tsx
> @86eq301bj #Added CAA Reviewer Page UI

- packages/core-library/contents/theme/theme.ts
> @86eq7g16f#reusable-alert-component-bug

- apps/web-backoffice-generic/src/pages/index.tsx
* Remove Login page directly in index and replace a login component
* Didn't delete login-route cause it will cascade to other code.
> @86eq8y8n5 #Remove login- page and replace login component

- apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramGridContent.tsx
- packages/core-library/components/Dialog/DialogBox.tsx
> @86eqdy2dr #Fix programlist modal on mobile view

- packages/core-library/components/Tabs/Tabs.tsx
> @86eqdy24m #minimal fix on tabs component

- apps/web-customer/src/components/blocks/ContactBlock/ContactForm.tsx
- apps/web-customer/src/components/blocks/LoginFormBlock/LoginForm.tsx
- packages/core-library/components/forms/PhoneField.tsx
- packages/core-library/components/forms/TextAreaField.tsx
> @86eqh0wkz#input-fields-design-adjustment

- packages/core-library/components/ErrorMap/ErrorMap.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudyCreation/CreateCaseStudyQuestion.tsx
- packages/core-library/tests/components/ErrorMap/ErrorMap.test.tsx
- yarn.lock
> @86eqeamyx #Enhanced Error Display in Case Study Creation

- apps/web-customer/src/components/blocks/HomePageBlocks/HowItWorks/HowItWorksBlock.tsx
> /@86eqddcbw #Step-by-step Card Consistency

- apps/web-backoffice-generic/src/pages/hub/chatbot/chatbot-management.tsx
- packages/core-library/system/app/internal/blocks/Hub/ChatbotManagement/ChatbotData.ts
- packages/core-library/system/app/internal/blocks/Hub/ChatbotManagement/ChatbotDialogs.tsx
- packages/core-library/system/app/internal/blocks/Hub/ChatbotManagement/ChatbotManagement.tsx
- packages/core-library/system/app/internal/blocks/Hub/ChatbotManagement/ChatbotManagementBlock.tsx
- packages/core-library/system/app/internal/blocks/Hub/ChatbotManagement/validation.ts
- packages/core-library/system/app/internal/blocks/index.ts
- packages/core-library/system/app/internal/parse-blocks.tsx
- packages/core-library/system/app/internal/types.ts
Chatbot Management Page UI (Mock data only)
Take note: Validations are just for preparations.
> @86eqe66hm #Added Chatbot Management Page UI

- apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
Maintenance mode page fixed button alignment and Responsiveness
MAC:
IPHONE:
TABLET:
> @86eqj928w #Maintenance-Page-Responsiveness

- apps/web-customer/src/components/blocks/HomePageBlocks/CoreZigmaSystem/CoreZigmaBlock.tsx
- apps/web-customer/src/components/blocks/HomePageBlocks/HowItWorks/HowItWorksBlock.tsx
- apps/web-customer/src/components/blocks/HomePageBlocks/Pricing/PricingBlock.tsx
- tailwind.ts
fixed how it works steps card responsiveness 
and adjust some size of text in mobile view 
responsiveness base on portrait view 
Before and after 
Before and after 
Retain view
> @86eqp8uxm #fixed How it works Step Card responsiveness

- apps/web-customer/package.json
- apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/WatchVideosBlock/WatchVideosBlock.tsx
- apps/web-customer/src/pages/hub/programs/body-systems/index.tsx
- apps/web-customer/src/pages/hub/programs/fastrack/index.tsx
- apps/web-customer/src/pages/hub/programs/patient-units/index.tsx
- packages/core-library/components/GenericSidebar/Sidebar.tsx
- packages/core-library/hooks/index.ts
- packages/core-library/hooks/useGetProgramList.ts
- packages/core-library/hooks/useUniqueById.ts
- packages/core-library/tests/components/Sidebar.test.tsx
- packages/core-library/tests/core/hooks/useGetProgramList.test.ts
- yarn.lock
> @86eqmv28u #Fix unauthenticated sidebar behavior

- apps/web-customer/src/components/blocks/ForgotPasswordBlock/ChangePasswordBlock/ChangePasswordForm.tsx
- apps/web-customer/src/components/blocks/ForgotPasswordBlock/ResetLinkBlock/ResetLinkBlock.tsx
- apps/web-customer/src/components/blocks/NotFoundBlock/NotFoundBlock.tsx
- apps/web-customer/src/pages/account/reset-password.tsx
> @86eqqwm29 #Reset Link & Change Password Page UI Enhancements

- apps/web-customer/src/components/blocks/LoginFormBlock/LoginForm.tsx
> @86eqnxzep #Login Page Adjustment

- apps/web-customer/src/components/blocks/LoginFormBlock/LoginFormBlock.tsx
the bug before 
login with uncheck remember me bug when login with uncheck remember me after logging out it went something wrong
after
can login with uncheck remember me and remove the encrypted password and email in form after logout
after logout with uncheck remember it clears the form
> @86eqhpc45 #fixed bug login uncheck

- packages/core-library/core/utils/contants/wc/HomePageData.ts
Change the link path from /about_us to /about
> @86eqhnnju #change the path from /about_us to /about

- apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
- apps/web-customer/src/pages/shared/Page.tsx
Before:
Web View:
Mobile View:
After:
Web View:
Mobile View:
> @86eqnxztj #Maintenance Mode UI Responsiveness

- apps/web-customer/src/pages/account/forgot-password.tsx
- apps/web-customer/src/pages/account/reset-link.tsx
- apps/web-customer/src/pages/account/verification/otp.tsx
- apps/web-customer/src/pages/customer/payment/checkout.tsx
Added useDesignVisibility in 
forgot-password page
reset-link page
otp page
checkout page
> @86eqqy6t6 #useDesignVisibility-Re-Implementation

- apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationForm.tsx
- yarn.lock
> @86eqrwt45 #WC Customer Registration Password Indicator

- apps/web-customer/src/components/blocks/HomePageBlocks/Pricing/PricingBlock.tsx
- apps/web-customer/src/components/blocks/HomePageBlocks/Pricing/PricingComponent/PricingCard.tsx
- apps/web-customer/src/constants/constants.ts
- packages/core-library/api/types.ts
Note: These are mock data only
This push includes:
Pricing Section:
Sub Tasks:
[FE] [Delivery Board Request] Pricing Section maximum of 2 items per programs
[FE] [Delivery Board Request] Pricing button alignment
[BUG] [FE] pricing list section "Get started" button design misaligned
[FE] [Delivery Board Request] Create Account Auto Scroll function is not Centered
[BUG] [FE] Pricing Section Design Alignment
https://github.com/user-attachments/assets/f62fe0b5-a394-4b9a-96fb-bc50e059a380
https://github.com/user-attachments/assets/b003d5eb-8c3b-4b74-88b5-27642277017a
> @86eqv670r #Pricing Section Bug and UI Improvement

- packages/core-library/api/web/web-api-backoffice.ts
- packages/core-library/contexts/BusinessQuery.tsx
- packages/core-library/core/hooks/useBusinessQueries.ts
- packages/core-library/system/app/internal/blocks/Hub/ContactUs/ContactUsManagement/ContactUsManagementBlock.tsx
- packages/core-library/system/app/internal/blocks/Hub/types.ts
Reverts NCLEXPower/nclexpower_turbo#535
> Revert "@86eqxwvp9 #Contact Us Table"

- apps/web-customer/src/components/blocks/ForgotPasswordBlock/ResetLinkBlock/ResetLinkBlock.tsx
- apps/web-customer/src/pages/account/reset-link.tsx
https://app.clickup.com/t/86eqx83t6
> @86eqx83t6 #Fix reset password scrollable and alignment

- apps/web-customer/src/components/blocks/DashboardBlock/Dashboard.tsx
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardAnalytics/AbilityAnalytics.tsx
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardAnalytics/CaseStudyAnalytics.tsx
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardAnalytics/ComprehensiveAnalytics.tsx
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardAnalytics/CurrentProgress.tsx
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardAnalytics/DashboardMock.ts
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardAnalytics/PerformanceIndicator.tsx
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardAnalytics/TestsTaken.tsx
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardAnalytics/TopicsCompleted.tsx
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardAnalytics/index.ts
- apps/web-customer/src/components/blocks/DashboardBlock/DashboardBlock.tsx
- apps/web-customer/src/pages/hub/index.tsx
`**[FE] [WC] Customer Dashboard**` : https://app.clickup.com/t/86eqyhfm5
> @86eqyhfm5 #Initial development on web customer dashboard

- apps/web-customer/src/components/blocks/ComingSoonBlock/ComingSoon.tsx
[DEV] [FE] Coming Soon Design Alignment on Figma Textfield : https://app.clickup.com/t/86er1rrcz
> @86er1rrcz #Adjusted the design based on the figma

- apps/web-customer/src/components/Skeleton/ProgramSkeletonLoader.tsx
- apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramGridView.tsx
- apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
- apps/web-customer/src/pages/hub/programs/body-systems/index.tsx
- apps/web-customer/src/pages/hub/programs/fastrack/index.tsx
- apps/web-customer/src/pages/hub/programs/patient-units/index.tsx
https://app.clickup.com/t/86eqxx86x
**Updated Picture**
loader is emitting wave of gray color from left to right.
> @86eqxx86x #added Program list skeleton loaders for List and Grid view

- apps/web-customer/src/components/blocks/LoginFormBlock/LoginForm.tsx
- packages/core-library/styles/global.css
removed yellow background when create one link is clicked
> @86eqx83ca #removed create one yellow background when clicked

- apps/web-customer/src/components/blocks/HomePageBlocks/RevolutionBanner/RevolutionBannerBlock.tsx
- packages/core-library/core/utils/contants/wc/HomePageData.ts
Image Carousel Banner Indicator Fixed as well as Slider Animation into 8 seconds
> @86er75bu3 #Fixed Home Banner Indicator and Animation Slider Every 8 secs

- packages/core-library/components/Button/IconButton.tsx
- packages/core-library/components/blocks/AnswerOptions/AnswerOptions.tsx
- packages/core-library/components/blocks/AnswerOptions/blocks/CaseStudy/MCQNoGroup/MCQNoGroup.tsx
- packages/core-library/components/blocks/AnswerOptions/blocks/CaseStudy/MCQNoGroup/components/MCQNoGroupAnswer.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/constants/constants.ts
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudySummary/component/Items/ItemContent.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudySummary/component/Items/MCQNoGroupSummary.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudySummary/component/Items/items.tsx
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/types.ts
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/utils/convertToCreateCaseStudy.ts
- packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/validation.ts
- packages/core-library/system/app/internal/types.ts
- packages/core-library/tests/components/Blocks/AnswerOptions/AnswerOptions.test.tsx
- packages/core-library/tests/components/Blocks/CasetStudy/MCQNoGroupSummary.test.tsx
- packages/core-library/tests/components/Blocks/CasetStudy/validation.test.ts
> @86er5gyz6 #Added MCQ No Group Case Study Type on WB

- apps/web-customer/src/components/blocks/LandingPageBlock/HomeBlock/HowItWorks/ModalComponent/ImageSection.tsx
Fixed the image responsiveness of watch videos
Before
After
> @86er8bwgf #fixed the responsiveness of watch videos

- packages/core-library/components/Textfield/SelectTextfield.tsx
- packages/core-library/system/app/internal/blocks/Hub/ManageUser/internal-users/CreateAccessRoute.tsx
- packages/core-library/system/app/internal/blocks/Hub/ManageUser/internal-users/InternalUsersBlock.tsx
- packages/core-library/system/app/internal/blocks/Hub/ManageUser/internal-users/InternalUsersForm.tsx
- packages/core-library/tests/components/SelectField/SelectField.test.tsx
- packages/core-library/tests/page/hub/mu/internal-users/CreateAccessRoute.test.tsx
- packages/core-library/tests/page/hub/mu/internal-users/InternalUsersForm.test.tsx
> @86eqww9hg #UAM user routes selection ui redesign

- apps/web-customer/src/components/payment-line/PaymentWalkthroughContext.tsx
- apps/web-customer/src/components/payment-line/steps/content/StripePaymentPage.tsx
> @86er8ktpy #resolved confirm payment button loading

- packages/core-library/contexts/PageLoaderContext.tsx
- packages/core-library/tests/contexts/PageLoaderContext.test.tsx
https://www.loom.com/share/778a0917009848cd9f8ca2af151a61eb?sid=be5fdf84-550b-44bb-a241-894c2c4d1ef4
> @86ercn3eh #Removed white screen when the page reloads

- packages/core-library/components/GenericDropDown/AccountMenu.tsx
- packages/core-library/components/GenericHeader/Header.tsx
> @86erfu9wk #fixed overlap search and menubar WC

- apps/web-customer/src/components/register-line/RegistrationWalkthroughForm.tsx
> @86erhdmdt #Added already have an account login link

- apps/web-customer/src/components/register-line/RegistrationWalkthroughForm.tsx
> @86erm0zvy #center the already have an account login and order summary

- packages/core-library/components/Dialog/CookieConsentDialog.tsx
> @86erbpay6/Upon login - Cookie Consent Bug

- packages/core-library/components/ReusableFooter/Footer.tsx
- removed yellow backgeround when clicked
- added text color change when hovered
> @86err28x9 #set bg to transparent added hover color

- packages/core-library/components/GenericDropDown/AccountMenu.tsx
- packages/core-library/components/GenericHeader/Header.tsx
- packages/core-library/components/GenericHeader/acoountMenuLoader.tsx
#changing icong from more-vertical to chevron-down-outline #removing white outline
#creating skeleton loader
> @86ern93v9 #removing searehbar in wc

- packages/core-library/components/Breadcrumbs/Breadcrumbs.tsx
removed the yellow background when "Programs" is clicked
> @86erqukdh #breadcrumbs yellow background removed

- apps/web-customer/src/components/ImageCarousel/ImageCarousel.tsx
- apps/web-customer/src/components/blocks/LandingPageBlock/HomeBlock/RevolutionBanner/RevolutionBannerBlock.tsx
- packages/core-library/core/utils/contants/wc/HomePageData.ts
- Removed the slick dots and created a custom dot indicator.
> @86erc6gx7 #Added custom dot indicator for carousel images in banner

- packages/core-library/components/ReusableFooter/Footer.tsx
Social media links will now open under new tab
> @86eruxw4w #social media links now opens on new tab

- packages/core-library/contents/theme/theme.ts
###REMOVE ALL YELLOW OUTLINE (COMPONENTS ETC)
ClickUp url: https://app.clickup.com/t/86erq0rbm
> @86erq0rbm #Remove All Yellow Outlines

- apps/web-customer/src/components/blocks/ForgotPasswordBlock/ForgotPasswordForm.tsx
- apps/web-customer/src/components/blocks/LandingPageBlock/AboutUsBlock/FAQBlock/FAQBlock.tsx
- apps/web-customer/src/components/blocks/LandingPageBlock/AboutUsBlock/FAQBlock/FAQItem.tsx
- apps/web-customer/src/components/blocks/LandingPageBlock/HomeBlock/HowItWorks/HowItWorksBlock.tsx
- apps/web-customer/src/components/blocks/LandingPageBlock/HomeBlock/HowItWorks/ModalComponent/ContentSection.tsx
- apps/web-customer/src/core/constant/AboutUsMock/FAQMock.ts
- [WC] [FE] Step by Step Cards (spacing, practice tests image, justify modal text and paragraph)
- [WC] [FE] FAQ collapse clickable, links redirection and remove 2 logo
- [WC] [FE] Forgot Password Back redirect to login
before:
after:
before:
after:
added redirection link to contact us page:
> @86erz6gc4 #Beta testing fixes

- apps/web-customer/src/middleware.ts
- All public routes now has /nclex eg. arxenius.com/nclex, arxenius.com/nclex/about etc.
> @86erzyy02 #Added nclex prefix to all public routes

- apps/web-customer/src/components/blocks/GoLive/GoLiveBlock.tsx
Clickup ID: [86et4t1z3](https://app.clickup.com/t/86et4t1z3)
Task - [FE] Change Alert to Toastify when sending notification
> @86et4t1z3 #Changed alert message to toastify

- packages/core-library/core/router.ts
> @86et9cvak # Change browser tab name

- packages/core-library/api/types.ts
- packages/core-library/api/web/web-api-backoffice.ts
- packages/core-library/system/app/internal/blocks/Hub/ComingSoon/ComingSoonManagement.tsx
- packages/core-library/system/app/internal/blocks/Hub/ComingSoon/ComingSoonManagementBlock.tsx
- packages/core-library/tests/components/ComingSoon/ComingSoonManagement.test.tsx
- packages/core-library/tests/components/ComingSoon/ComingSoonManagementBlock.test.tsx
> @86et4tu46 #Country list with country code API integration
